const daftarMateri = [
  {
    nama: "Huruf Hijaiyah",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "ا", latin: "Alif" },
      { arab: "ب", latin: "Ba" },
      { arab: "ت", latin: "Ta" },
      { arab: "ث", latin: "Tsa" },
      { arab: "ج", latin: "Jim" },
      { arab: "ح", latin: "Ha" },
      { arab: "خ", latin: "Kha" },
      { arab: "د", latin: "Dal" },
      { arab: "ذ", latin: "Dzal" },
      { arab: "ر", latin: "Ra" },
      { arab: "ز", latin: "Zai" },
      { arab: "س", latin: "Sin" },
      { arab: "ش", latin: "Syin" },
      { arab: "ص", latin: "Shad" },
      { arab: "ض", latin: "Dhad" },
      { arab: "ط", latin: "Tha" },
      { arab: "ظ", latin: "Zha" },
      { arab: "ع", latin: "'Ain" },
      { arab: "غ", latin: "Ghain" },
      { arab: "ف", latin: "Fa" },
      { arab: "ق", latin: "Qaf" },
      { arab: "ك", latin: "Kaf" },
      { arab: "ل", latin: "Lam" },
      { arab: "م", latin: "Mim" },
      { arab: "ن", latin: "Nun" },
      { arab: "و", latin: "Wawu" },
      { arab: "ه", latin: "Ha" },
      { arab: "ء", latin: "Hamzah" },
      { arab: "ي", latin: "Ya" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Fathah",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اَ", latin: "a" },
      { arab: "بَ", latin: "ba" },
      { arab: "تَ", latin: "ta" },
      { arab: "ثَ", latin: "ṡa" },
      { arab: "جَ", latin: "ja" },
      { arab: "حَ", latin: "ḥa" },
      { arab: "خَ", latin: "kha" },
      { arab: "دَ", latin: "da" },
      { arab: "ذَ", latin: "ża" },
      { arab: "رَ", latin: "ra" },
      { arab: "زَ", latin: "za" },
      { arab: "سَ", latin: "sa" },
      { arab: "شَ", latin: "sya" },
      { arab: "صَ", latin: "ṣa" },
      { arab: "ضَ", latin: "ḍa" },
      { arab: "طَ", latin: "ṭa" },
      { arab: "ظَ", latin: "ẓa" },
      { arab: "عَ", latin: "'a" },
      { arab: "غَ", latin: "gha" },
      { arab: "فَ", latin: "fa" },
      { arab: "قَ", latin: "qa" },
      { arab: "كَ", latin: "ka" },
      { arab: "لَ", latin: "la" },
      { arab: "مَ", latin: "ma" },
      { arab: "نَ", latin: "na" },
      { arab: "وَ", latin: "wa" },
      { arab: "هَ", latin: "ha" },
      { arab: "ءَ", latin: "a" },
      { arab: "يَ", latin: "ya" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Kasrah",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اِ", latin: "i" },
      { arab: "بِ", latin: "bi" },
      { arab: "تِ", latin: "ti" },
      { arab: "ثِ", latin: "ṡi" },
      { arab: "جِ", latin: "ji" },
      { arab: "حِ", latin: "ḥi" },
      { arab: "خِ", latin: "khi" },
      { arab: "دِ", latin: "di" },
      { arab: "ذِ", latin: "żi" },
      { arab: "رِ", latin: "ri" },
      { arab: "زِ", latin: "zi" },
      { arab: "سِ", latin: "si" },
      { arab: "شِ", latin: "syi" },
      { arab: "صِ", latin: "ṣi" },
      { arab: "ضِ", latin: "ḍi" },
      { arab: "طِ", latin: "ṭi" },
      { arab: "ظِ", latin: "ẓi" },
      { arab: "عِ", latin: "'i" },
      { arab: "غِ", latin: "ghi" },
      { arab: "فِ", latin: "fi" },
      { arab: "قِ", latin: "qi" },
      { arab: "كِ", latin: "ki" },
      { arab: "لِ", latin: "li" },
      { arab: "مِ", latin: "mi" },
      { arab: "نِ", latin: "ni" },
      { arab: "وِ", latin: "wi" },
      { arab: "هِ", latin: "hi" },
      { arab: "ءِ", latin: "i" },
      { arab: "يِ", latin: "yi" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Dhammah",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اُ", latin: "u" },
      { arab: "بُ", latin: "bu" },
      { arab: "تُ", latin: "tu" },
      { arab: "ثُ", latin: "ṡu" },
      { arab: "جُ", latin: "ju" },
      { arab: "حُ", latin: "ḥu" },
      { arab: "خُ", latin: "khu" },
      { arab: "دُ", latin: "du" },
      { arab: "ذُ", latin: "żu" },
      { arab: "رُ", latin: "ru" },
      { arab: "زُ", latin: "zu" },
      { arab: "سُ", latin: "su" },
      { arab: "شُ", latin: "syu" },
      { arab: "صُ", latin: "ṣu" },
      { arab: "ضُ", latin: "ḍu" },
      { arab: "طُ", latin: "ṭu" },
      { arab: "ظُ", latin: "ẓu" },
      { arab: "عُ", latin: "'u" },
      { arab: "غُ", latin: "ghu" },
      { arab: "فُ", latin: "fu" },
      { arab: "قُ", latin: "qu" },
      { arab: "كُ", latin: "ku" },
      { arab: "لُ", latin: "lu" },
      { arab: "مُ", latin: "mu" },
      { arab: "نُ", latin: "nu" },
      { arab: "وُ", latin: "wu" },
      { arab: "هُ", latin: "hu" },
      { arab: "ءُ", latin: "u" },
      { arab: "يُ", latin: "yu" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Tanwin Fathatain",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اً", latin: "an" },
      { arab: "بًا", latin: "ban" },
      { arab: "تًا", latin: "tan" },
      { arab: "ثًا", latin: "ṡan" },
      { arab: "جًا", latin: "jan" },
      { arab: "حًا", latin: "ḥan" },
      { arab: "خًا", latin: "khan" },
      { arab: "دًا", latin: "dan" },
      { arab: "ذًا", latin: "żan" },
      { arab: "رًا", latin: "ran" },
      { arab: "زًا", latin: "zan" },
      { arab: "سًا", latin: "san" },
      { arab: "شًا", latin: "syan" },
      { arab: "صًا", latin: "ṣan" },
      { arab: "ضًا", latin: "ḍan" },
      { arab: "طًا", latin: "ṭan" },
      { arab: "ظًا", latin: "ẓan" },
      { arab: "عًا", latin: "'an" },
      { arab: "غًا", latin: "ghan" },
      { arab: "فًا", latin: "fan" },
      { arab: "قًا", latin: "qan" },
      { arab: "كًا", latin: "kan" },
      { arab: "لًا", latin: "lan" },
      { arab: "مًا", latin: "man" },
      { arab: "نًا", latin: "nan" },
      { arab: "وًا", latin: "wan" },
      { arab: "هًا", latin: "han" },
      { arab: "ءً", latin: "an" },
      { arab: "يًا", latin: "yan" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Tanwin Kasratain",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "ٍا", latin: "in" },
      { arab: "بٍ", latin: "bin" },
      { arab: "تٍ", latin: "tin" },
      { arab: "ثٍ", latin: "ṡin" },
      { arab: "جٍ", latin: "jin" },
      { arab: "حٍ", latin: "ḥin" },
      { arab: "خٍ", latin: "khin" },
      { arab: "دٍ", latin: "din" },
      { arab: "ذٍ", latin: "żin" },
      { arab: "رٍ", latin: "rin" },
      { arab: "زٍ", latin: "zin" },
      { arab: "سٍ", latin: "sin" },
      { arab: "شٍ", latin: "syin" },
      { arab: "صٍ", latin: "ṣin" },
      { arab: "ضٍ", latin: "ḍin" },
      { arab: "طٍ", latin: "ṭin" },
      { arab: "ظٍ", latin: "ẓin" },
      { arab: "عٍ", latin: "'in" },
      { arab: "غٍ", latin: "ghin" },
      { arab: "فٍ", latin: "fin" },
      { arab: "قٍ", latin: "qin" },
      { arab: "كٍ", latin: "kin" },
      { arab: "لٍ", latin: "lin" },
      { arab: "مٍ", latin: "min" },
      { arab: "نٍ", latin: "nin" },
      { arab: "وٍ", latin: "win" },
      { arab: "هٍ", latin: "hin" },
      { arab: "ءٍ", latin: "in" },
      { arab: "يٍ", latin: "yin" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Tanwin Dhammatain",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اٌ", latin: "un" },
      { arab: "بٌ", latin: "bun" },
      { arab: "تٌ", latin: "tun" },
      { arab: "ثٌ", latin: "ṡun" },
      { arab: "جٌ", latin: "jun" },
      { arab: "حٌ", latin: "ḥun" },
      { arab: "خٌ", latin: "khun" },
      { arab: "دٌ", latin: "dun" },
      { arab: "ذٌ", latin: "żun" },
      { arab: "رٌ", latin: "run" },
      { arab: "زٌ", latin: "zun" },
      { arab: "سٌ", latin: "sun" },
      { arab: "شٌ", latin: "syun" },
      { arab: "صٌ", latin: "ṣun" },
      { arab: "ضٌ", latin: "ḍun" },
      { arab: "طٌ", latin: "ṭun" },
      { arab: "ظٌ", latin: "ẓun" },
      { arab: "عٌ", latin: "'un" },
      { arab: "غٌ", latin: "ghun" },
      { arab: "فٌ", latin: "fun" },
      { arab: "قٌ", latin: "qun" },
      { arab: "كٌ", latin: "kun" },
      { arab: "لٌ", latin: "lun" },
      { arab: "مٌ", latin: "mun" },
      { arab: "نٌ", latin: "nun" },
      { arab: "وٌ", latin: "wun" },
      { arab: "هٌ", latin: "hun" },
      { arab: "ءٌ", latin: "un" },
      { arab: "يٌ", latin: "yun" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Sukun",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اَاْ", latin: "a’ / ā" },
      { arab: "اَبْ", latin: "ab" },
      { arab: "اَتْ", latin: "at" },
      { arab: "اَثْ", latin: "aṡ" },
      { arab: "اَجْ", latin: "aj" },
      { arab: "اَحْ", latin: "aḥ" },
      { arab: "اَخْ", latin: "akh" },
      { arab: "اَدْ", latin: "ad" },
      { arab: "اَذْ", latin: "aż" },
      { arab: "اَرْ", latin: "ar" },
      { arab: "اَزْ", latin: "az" },
      { arab: "اَسْ", latin: "as" },
      { arab: "اَشْ", latin: "asy" },
      { arab: "اَصْ", latin: "aṣ" },
      { arab: "اَضْ", latin: "aḍ" },
      { arab: "اَطْ", latin: "aṭ" },
      { arab: "اَظْ", latin: "aẓ" },
      { arab: "اَعْ", latin: "a‘" },
      { arab: "اَغْ", latin: "agh" },
      { arab: "اَفْ", latin: "af" },
      { arab: "اَقْ", latin: "aq" },
      { arab: "اَكْ", latin: "ak" },
      { arab: "اَلْ", latin: "al" },
      { arab: "اَمْ", latin: "am" },
      { arab: "اَنْ", latin: "an" },
      { arab: "اَوْ", latin: "au / aw" },
      { arab: "اَهْ", latin: "ah" },
      { arab: "اَءْ", latin: "a’" },
      { arab: "اَيْ", latin: "ai / ay" }
    ]
  },
  {
    nama: "Huruf Hijaiyah Tasydid",
    jenis: "huruf-hijaiyah",
    items: [
      { arab: "اَاَّ", latin: "a’'a" },
      { arab: "اَبَّ", latin: "abba" },
      { arab: "اَتَّ", latin: "atta" },
      { arab: "اَثَّ", latin: "aṡṡa" },
      { arab: "اَجَّ", latin: "ajja" },
      { arab: "اَحَّ", latin: "aḥḥa" },
      { arab: "اَخَّ", latin: "akhkha" },
      { arab: "اَدَّ", latin: "adda" },
      { arab: "اَذَّ", latin: "ażża" },
      { arab: "اَرَّ", latin: "arra" },
      { arab: "اَزَّ", latin: "azza" },
      { arab: "اَسَّ", latin: "assa" },
      { arab: "اَشَّ", latin: "asysya" },
      { arab: "اَصَّ", latin: "aṣṣa" },
      { arab: "اَضَّ", latin: "aḍḍa" },
      { arab: "اَطَّ", latin: "aṭṭa" },
      { arab: "اَظَّ", latin: "aẓẓa" },
      { arab: "اَعَّ", latin: "a‘‘a" },
      { arab: "اَغَّ", latin: "aghgha" },
      { arab: "اَفَّ", latin: "affa" },
      { arab: "اَقَّ", latin: "aqqa" },
      { arab: "اَكَّ", latin: "akka" },
      { arab: "اَلَّ", latin: "alla" },
      { arab: "اَمَّ", latin: "amma" },
      { arab: "اِنَّ", latin: "inna" },
      { arab: "اَوَّ", latin: "awwa" },
      { arab: "اَهَّ", latin: "ahha" },
      { arab: "اَءَّ", latin: "a’’a" },
      { arab: "اَيَّ", latin: "ayya" }
    ]
  }
];
